language: python
python:
    - "2.7"
    - "3.5"
install:
    - pip install -r requirements.txt
before_install:
    - sudo apt-get update
    - sudo apt-get build-dep python-pygame
    - sudo apt-get install mercurial
script: nosetests
